/* data.js — منبع دادهٔ مشترک بین صفحات */

const DATA = {

    /* ---------- پروفایل ---------- */
    profile: {
        name: 'محمد اکبری',
        handle: 'akbarjimi',
        role: 'توسعه‌دهندهٔ بک‌اند PHP و Laravel',
        since: 1397,
        location: 'تهران',
        goodreads: 'https://www.goodreads.com/user/show/',
    },

    /* ---------- پروژه‌ها ---------- */
    projects: [
        {
            id: 'purser',
            title: 'Purser',
            subtitle: 'Laravel Excel Importer',
            icon: '📥',
            description: 'خط لولهٔ توزیع‌شده و رویدادمحور برای ایمپورت اکسل در Laravel؛ با درایورهای قابل تعویض، اعتبارسنجی سطر به سطر و بازیابی خطای مستقل.',
            tags: ['Laravel', 'PHP', 'Queue', 'Excel'],
            url: 'purser.html',
            repo: 'https://github.com/akbarjimi/excel-importer-pipeline',
            packagist: 'https://packagist.org/packages/akbarjimi/purser',
            year: 1404,
            featured: true,
            internal: true,
        },
        {
            id: 'leetcode',
            title: 'راه‌حل‌های LeetCode در Go',
            icon: '🧠',
            description: 'مخزنی از راه‌حل‌های چالش‌های LeetCode که با زبان Go نوشته و مستند شده‌اند؛ همراه با تست و توضیح الگوریتم.',
            tags: ['Go', 'Algorithm', 'LeetCode'],
            url: 'https://github.com/akbarjimi/leetcode',
            repo: 'https://github.com/akbarjimi/leetcode',
            year: 1404,
            featured: true,
            internal: false,
        },
        {
            id: 'faiss',
            title: 'کدهای دورهٔ FAISS',
            icon: '🔍',
            description: 'مخزن کد و مثال‌های دورهٔ «آموزش جامع FAISS: طراحی و پیاده‌سازی موتورهای جستجوی برداری».',
            tags: ['Python', 'FAISS', 'Vector Search'],
            url: 'https://github.com/akbarjimi/FAISS',
            repo: 'https://github.com/akbarjimi/FAISS',
            year: 1404,
            featured: true,
            internal: false,
        },
    ],

    /* ---------- دوره‌ها ---------- */
    courses: [
        {
            id: 'faiss-course',
            title: 'آموزش جامع FAISS: طراحی و پیاده‌سازی موتورهای جستجوی برداری',
            subtitle: 'Vector Search · از مبانی ریاضی تا معماری سیستم‌های مقیاس‌پذیر',
            platform: 'مکتب‌خونه',
            duration: '۱ ساعت و ۵۳ دقیقه',
            level: 'مقدماتی تا پیشرفته',
            students: 62,
            rating: 4.7,
            ratingCount: 9,
            reviewCount: 2,
            updatedAt: 'مرداد ۱۴۰۵',
            description: 'یک دورهٔ پروژه‌محور برای آشنایی با معماری و پیاده‌سازی FAISS؛ از الگوریتم‌های پایهٔ K-Means تا گراف‌های HNSW و فشرده‌سازی IVF-PQ.',
            tags: ['FAISS', 'Python', 'Vector Search', 'HNSW', 'IVF-PQ', 'GPU'],
            url: 'https://maktabkhooneh.org/course-preview/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D8%AC%D8%B3%D8%AA%D8%AC%D9%88%DB%8C-%D8%A8%D8%B1%D8%AF%D8%A7%D8%B1%DB%8C-%DA%A9%D9%85%DA%A9-%DA%A9%D8%AA%D8%A7%D8%A8%D8%AE%D8%A7%D9%86%D9%87-mk16732/?v=1',
            repo: 'https://github.com/akbarjimi/FAISS',
            year: 1404,
            featured: true,
            internal: true,
            page: 'courses.html#faiss',
        },
    ],

    /* ---------- نوشته‌های بلند ---------- */
    posts: [
        {
            id: 'asimov',
            title: 'مسیر من تا بنیاد',
            subtitle: 'از وبلاگ‌های قدیمی تا آسیموف: سفری به دنیای علمی‌تخیلی',
            excerpt: 'چطور کنجکاوی در وبلاگ‌های قدیمی فارسی، مرا به یکی از بنیادی‌ترین آثار علمی‌تخیلی تاریخ رساند؛ جستاری شخصی دربارهٔ کشف آسیموف و تحلیل کتاب «بنیاد».',
            date: '1404-05-12',
            readingTime: '۹ دقیقه',
            tags: ['کتاب', 'علمی‌تخیلی', 'آسیموف'],
            url: 'blog.html#asimov',
        },
        {
            id: 'mind-and-market',
            title: 'یادداشتی بر «ذهن و بازار: سرمایه‌داری در اندیشهٔ غربی»',
            excerpt: 'جری مولر در این کتاب نشان می‌دهد چگونه متفکران غربی در دو سده، میان بازار و ذهن انسان پلی برقرار کردند.',
            date: '1404-03-20',
            readingTime: '۷ دقیقه',
            tags: ['کتاب', 'اقتصاد', 'اندیشه'],
            url: 'blog.html#mind-and-market',
        },
        {
            id: 'emperor-of-all-maladies',
            title: 'یادداشتی بر «امپراتور همه‌ی بیماری‌ها: زندگی‌نامهٔ سرطان»',
            excerpt: 'روایتی حماسی از تاریخ سرطان؛ از جراحی‌های بی‌رحمانهٔ قرن نوزدهم تا درمان‌های هدفمند امروز.',
            date: '1404-01-08',
            readingTime: '۸ دقیقه',
            tags: ['کتاب', 'پزشکی', 'تاریخ'],
            url: 'blog.html#emperor-of-all-maladies',
        },
    ],

    /* ---------- یادداشت‌های کوتاه ---------- */
    notes: [
        {
            id: 'abbas-mirza-tomb',
            date: '1405-01-13',
            text: 'چقدر فروتنانه! سنگ قبر عباس میرزا قاجار، فرماندهٔ سپاه ایران در جنگ‌های ایران و روس.',
            image: 'assets/notes/abbas-mirza-tomb.jpg',
            imageAlt: 'سنگ قبر عباس میرزا قاجار',
            imageCaption: 'سنگ قبر عباس میرزا قاجار',
        },
        {
            id: 'movie-search-tip',
            date: '1404-12-26',
            text: 'این لینک یک فهرست از ۵۰۰۰ فیلم برتره. برو داخلش و فیلمی که می‌خوای رو با «یافتن در صفحه» پیدا کن — Ctrl+F در ویندوز یا Cmd+F در مک.',
            link: {
                url: 'https://dls6.iran-gamecenter-host.com/DonyayeSerial/top_5000_movies.html',
                title: 'فهرست ۵۰۰۰ فیلم برتر',
                host: 'dls6.iran-gamecenter-host.com',
            },
        },
        {
            id: 'abbas-telegram',
            date: '1404-12-13',
            text: 'اون موقع که هیچ‌کدوم‌مون اینترنت نداشتیم، عباس آقا داشت توی کانال تلگرامش پست می‌ذاشت!',
            image: 'assets/notes/abbas-telegram.jpg',
            imageAlt: 'تصویر خبری دربارهٔ عباس آخوندی',
        },
    ],

    /* ---------- فیلم‌ها ---------- */
    movies: [
        {
            id: 'tuner',
            title: 'Tuner',
            titleFa: 'تیونر',
            year: 2025,
            rating: 7.2,
            runtime: 109,
            director: 'Daniel Roher',
            cast: ['داستین هافمن', 'ژان رنو'],
            genres: ['درام'],
            country: null,
            language: 'انگلیسی',
            poster: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0Kmt7LvUUpl8McRLnngodQRYP5XcfpM9NdHMnozMnzr7DmsVTQyAceCgr&s=10',
            summary: 'فیلمی با بازی داستین هافمن.',
            note: null,
            watchedAt: '1405-07',
            trakt: 'https://app.trakt.tv/movies/tuner-2026',
        },
    ],

    /* ---------- سریال‌ها ---------- */
    series: [
        {
            id: 'vahshi', title: 'Vahshi', titleFa: 'وحشی',
            year: null, endYear: null, rating: null,
            seasons: null, episodes: null,
            status: 'completed', timesWatched: 1,
            genres: ['درام', 'ایرانی'], country: 'ایران', language: 'فارسی',
            network: 'فیلیمو', creator: null, cast: [], poster: '',
            summary: 'سریالی ایرانی که در مرداد ۱۴۰۵ روی فیلیمو تماشا کردم و بسیار پسندیدم.',
            note: null, watchedAt: '1405-05', trakt: null,
        },
        {
            id: 'mare-of-easttown', title: 'Mare of Easttown', titleFa: 'مِیر آو ایست‌تاون',
            year: 2021, endYear: 2021, rating: 8.4,
            seasons: 1, episodes: 7,
            status: 'completed', timesWatched: 1,
            genres: ['جنایی', 'درام', 'معمایی'], country: 'آمریکا', language: 'انگلیسی',
            network: 'HBO', creator: 'Brad Ingelsby',
            cast: ['کیت وینسلت', 'جولین نیکلسون', 'جین اسمارت'], poster: '',
            summary: 'مینی‌سریالی جنایی با بازی کیت وینسلت در نقش کارآگاهی که در شهر کوچکی با پرونده‌ای پیچیده روبه‌رو می‌شود.',
            note: null, watchedAt: '1405-03', trakt: null,
        },
        {
            id: 'ted-lasso', title: 'Ted Lasso', titleFa: 'تد لاسو',
            year: 2020, endYear: 2023, rating: 8.8,
            seasons: 3, episodes: 34,
            status: 'completed', timesWatched: 1,
            genres: ['کمدی', 'درام', 'ورزشی'], country: 'آمریکا', language: 'انگلیسی',
            network: 'Apple TV+', creator: 'Bill Lawrence',
            cast: ['جیسون سودیکیس', 'هانا وادینگهام', 'برت گلدشتاین'], poster: '',
            summary: 'مربی فوتبال آمریکایی‌ای که برای هدایت یک تیم انگلیسی استخدام می‌شود؛ سریالی گرم و امیدوارکننده.',
            note: 'تیر ۱۴۰۴ تماشا کردم و خیلی دوستش داشتم.',
            watchedAt: '1404-04', trakt: null,
        },
        {
            id: 'sharp-objects', title: 'Sharp Objects', titleFa: 'اشیای تیز',
            year: 2018, endYear: 2018, rating: 8.1,
            seasons: 1, episodes: 8,
            status: 'completed', timesWatched: 1,
            genres: ['جنایی', 'درام', 'معمایی'], country: 'آمریکا', language: 'انگلیسی',
            network: 'HBO', creator: 'Marti Noxon',
            cast: ['ایمی آدامز', 'پاتریشیا کلارکسون'], poster: '',
            summary: 'مینی‌سریالی روان‌شناختی با بازی ایمی آدامز در نقش روزنامه‌نگاری که برای پوشش قتل‌های زنجیره‌ای به زادگاهش بازمی‌گردد.',
            note: 'مهر و آبان پارسال تماشا کردم.',
            watchedAt: '1404-08', trakt: null,
        },
        {
            id: 'friends', title: 'Friends', titleFa: 'فرندز',
            year: 1994, endYear: 2004, rating: 8.9,
            seasons: 10, episodes: 236,
            status: 'rewatched', timesWatched: 4,
            genres: ['کمدی', 'عاشقانه'], country: 'آمریکا', language: 'انگلیسی',
            network: 'NBC', creator: 'David Crane, Marta Kauffman',
            cast: ['جنیفر آنیستون', 'کورتنی کاکس', 'لیسا کادرو', 'مت له‌بلانک', 'متیو پری', 'دیوید شویمر'], poster: '',
            summary: 'شش دوست در نیویورک؛ یکی از محبوب‌ترین سیتکام‌های تاریخ تلویزیون.',
            note: 'چهار بار تا انتها دیده‌ام.',
            watchedAt: null, trakt: null,
        },
        {
            id: 'big-bang-theory', title: 'The Big Bang Theory', titleFa: 'تئوری بیگ بنگ',
            year: 2007, endYear: 2019, rating: 8.2,
            seasons: 12, episodes: 279,
            status: 'rewatched', timesWatched: 4,
            genres: ['کمدی'], country: 'آمریکا', language: 'انگلیسی',
            network: 'CBS', creator: 'Chuck Lorre, Bill Prady',
            cast: ['جانی گالکی', 'جیم پارسونز', 'کیلی کواکو', 'سایمون هلبرگ'], poster: '',
            summary: 'چند دانشمند و همسایه‌شان در پاسادینا؛ سیتکامی دربارهٔ دوستی، علم و عشق.',
            note: 'چهار بار تا انتها دیده‌ام.',
            watchedAt: null, trakt: null,
        },
        {
            id: 'breaking-bad', title: 'Breaking Bad', titleFa: 'بریکینگ بد',
            year: 2008, endYear: 2013, rating: 9.5,
            seasons: 5, episodes: 62,
            status: 'completed', timesWatched: 1,
            genres: ['جنایی', 'درام', 'هیجان‌انگیز'], country: 'آمریکا', language: 'انگلیسی',
            network: 'AMC', creator: 'Vince Gilligan',
            cast: ['برایان کرانستون', 'آرون پاول', 'آنا گان'], poster: '',
            summary: 'معلم شیمی دبیرستانی که پس از تشخیص سرطان، به تولید متامفتامین روی می‌آورد.',
            note: 'یک بار دیدم و عاشقش شدم.',
            watchedAt: null, trakt: null,
        },
        {
            id: 'game-of-thrones', title: 'Game of Thrones', titleFa: 'بازی تاج و تخت',
            year: 2011, endYear: 2019, rating: 9.2,
            seasons: 8, episodes: 73,
            status: 'completed', timesWatched: 1,
            genres: ['فانتزی', 'درام', 'ماجراجویی'], country: 'آمریکا', language: 'انگلیسی',
            network: 'HBO', creator: 'David Benioff, D.B. Weiss',
            cast: ['امیلیا کلارک', 'کیت هرینگتون', 'پیتر دینکلیج'], poster: '',
            summary: 'اقتباسی فانتزی از رمان‌های جرج آر. آر. مارتین؛ نبردی برای تصاحب تخت آهنین.',
            note: 'یک بار دیدم و خیلی دوستش داشتم.',
            watchedAt: null, trakt: null,
        },
        {
            id: 'house-of-cards', title: 'House of Cards', titleFa: 'خانهٔ پوشالی',
            year: 2013, endYear: 2018, rating: 8.6,
            seasons: 6, episodes: 73,
            status: 'dropped', timesWatched: 1,
            genres: ['درام', 'سیاسی', 'هیجان‌انگیز'], country: 'آمریکا', language: 'انگلیسی',
            network: 'Netflix', creator: 'Beau Willimon',
            cast: ['کوین اسپیسی', 'رابین رایت'], poster: '',
            summary: 'فرانک آندروود و همسرش کلر، در مسیر قدرت در واشینگتن.',
            note: 'فصل آخرش را ندیدم.',
            watchedAt: null, trakt: null,
        },
        {
            id: 'prison-break', title: 'Prison Break', titleFa: 'فرار از زندان',
            year: 2005, endYear: 2017, rating: 8.3,
            seasons: 5, episodes: 90,
            status: 'completed', timesWatched: 1,
            genres: ['جنایی', 'درام', 'هیجان‌انگیز'], country: 'آمریکا', language: 'انگلیسی (دوبله فارسی)',
            network: 'Fox', creator: 'Paul Scheuring',
            cast: ['ونتورث میلر', 'دامینیک پرسل'], poster: '',
            summary: 'مایکل اسکافیلد نقشه‌ای دقیق می‌کشد تا برادرش را از زندان نجات دهد.',
            note: 'نسخهٔ دوبلهٔ فارسی‌اش را دیدم.',
            watchedAt: null, trakt: null,
        },
        {
            id: 'ghahve-talkh', title: 'Ghahve-ye Talkh', titleFa: 'قهوهٔ تلخ',
            year: 1389, endYear: 1395, rating: null,
            seasons: 5, episodes: null,
            status: 'rewatched', timesWatched: 2,
            genres: ['کمدی', 'ایرانی'], country: 'ایران', language: 'فارسی',
            network: 'نمایش خانگی', creator: 'مهران مدیری',
            cast: ['مهران مدیری', 'سیامک انصاری', 'جواد عزتی'], poster: '',
            summary: 'مجموعهٔ طنز مهران مدیری با نگاهی هجوآمیز به جامعهٔ ایرانی.',
            note: 'دو بار تا انتها دیده‌ام.',
            watchedAt: null, trakt: null,
        },
        {
            id: 'shabhaye-barareh', title: 'Shabhaye Barareh', titleFa: 'شب‌های برره',
            year: 1384, endYear: 1384, rating: null,
            seasons: 1, episodes: null,
            status: 'completed', timesWatched: 1,
            genres: ['کمدی', 'ایرانی'], country: 'ایران', language: 'فارسی',
            network: 'شبکه سه', creator: 'مهران مدیری',
            cast: ['مهران مدیری', 'سیامک انصاری', 'سعید پیردوست'], poster: '',
            summary: 'مجموعهٔ طنز مهران مدیری که در دهکده‌ای خیالی به نام برره می‌گذرد.',
            note: 'خیلی دوستش داشتم.',
            watchedAt: null, trakt: null,
        },
        {
            id: 'seh-dar-chahar', title: 'Seh dar Chahar', titleFa: 'سه در چهار',
            year: 1387, endYear: 1387, rating: null,
            seasons: 1, episodes: null,
            status: 'rewatched', timesWatched: 3,
            genres: ['کمدی', 'ایرانی'], country: 'ایران', language: 'فارسی',
            network: 'شبکه یک', creator: null, cast: [], poster: '',
            summary: 'مجموعهٔ طنز شبکهٔ یک سیما که در سال ۱۳۸۷ پخش شد.',
            note: 'چندین بار دیده‌ام.',
            watchedAt: null, trakt: null,
        },
    ],

    /* ---------- کتاب‌ها ---------- */
    /* فیلدها:
       - rating       امتیاز شخصی شما (۱ تا ۵)، اگر null باشد یعنی امتیاز نداده‌اید
       - avgRating    میانگین امتیاز Goodreads
       - finishedAt   تاریخ خواندن (شمسی، YYYY-MM-DD)
       - pages        تعداد صفحه
       - genres       برچسب‌های ژانر
    */
    books: [
        /* ——— ۱۴۰۵ ——— */
        {
            id: 'ivan-ilyich',
            title: 'The Death of Ivan Ilyich',
            titleFa: 'مرگ ایوان ایلیچ',
            author: 'Leo Tolstoy',
            authorFa: 'لئو تولستوی',
            year: 1886,
            rating: 3,
            avgRating: 4.14,
            pages: 86,
            genres: ['کلاسیک', 'فلسفی', 'روسی'],
            language: 'روسی',
            cover: '',
            summary: 'روایتی کوتاه و تکان‌دهنده از مرگ یک قاضی روس و پرسش‌های او دربارهٔ معنای زندگی.',
            note: null,
            finishedAt: '1405-06-16',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'emperor-of-all-maladies',
            title: 'The Emperor of All Maladies',
            titleFa: 'سرطان، امپراتور بیماری‌ها',
            subtitle: 'زندگی‌نامهٔ سرطان',
            author: 'Siddhartha Mukherjee',
            authorFa: 'سیدهارتا موکرجی',
            year: 2010,
            rating: 5,
            avgRating: 4.34,
            pages: 592,
            genres: ['علمی', 'تاریخ', 'پزشکی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'روایتی حماسی از تاریخ سرطان؛ از جراحی‌های بی‌رحمانهٔ قرن نوزدهم تا درمان‌های هدفمند امروز.',
            note: 'یکی از تأثیرگذارترین کتاب‌های غیرداستانی‌ای که خوانده‌ام.',
            finishedAt: '1405-04-28',
            startedAt: '1405-02',
            goodreads: null,
        },
        {
            id: 'foundation',
            title: 'Foundation',
            titleFa: 'بنیاد',
            author: 'Isaac Asimov',
            authorFa: 'آیزاک آسیموف',
            year: 1951,
            rating: 4,
            avgRating: 4.17,
            pages: 244,
            genres: ['علمی‌تخیلی', 'کلاسیک'],
            language: 'انگلیسی',
            cover: '',
            summary: 'امپراتوری کهکشانی در حال سقوط؛ هری سلدون علم روان‌تاریخ را برای کوتاه کردن عصر تاریکی بنیان می‌گذارد.',
            note: null,
            finishedAt: '1405-04-15',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'guns-germs-steel',
            title: 'Guns, Germs, and Steel',
            titleFa: 'تفنگ‌ها، میکروب‌ها و فولاد',
            author: 'Jared Diamond',
            authorFa: 'جرد دایموند',
            year: 1997,
            rating: null,
            avgRating: 4.04,
            pages: 480,
            genres: ['تاریخ', 'انسان‌شناسی', 'علمی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'چرا تمدن‌های اوراسیایی بر دیگران چیره شدند؟ پاسخ در جغرافیا، نه در نژاد.',
            note: null,
            finishedAt: '1405-01',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'invincible',
            title: 'The Invincible',
            titleFa: 'شکست‌ناپذیر',
            author: 'Stanisław Lem',
            authorFa: 'استانیسلاو لم',
            year: 1964,
            rating: null,
            avgRating: 4.15,
            pages: 224,
            genres: ['علمی‌تخیلی', 'فلسفی'],
            language: 'لهستانی',
            cover: '',
            summary: 'کاوش سفینه‌ای در سیاره‌ای که حیاتش از جنس دیگری است؛ شاهکاری از لم دربارهٔ مرزهای شناخت.',
            note: null,
            finishedAt: '1405-01-26',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'political-order-decay',
            title: 'Political Order and Political Decay',
            titleFa: 'نظم و زوال سیاسی',
            author: 'Francis Fukuyama',
            authorFa: 'فرانسیس فوکویاما',
            year: 2014,
            rating: null,
            avgRating: 4.34,
            pages: 668,
            genres: ['سیاسی', 'تاریخ', 'اندیشه'],
            language: 'انگلیسی',
            cover: '',
            summary: 'جلد دوم «منشأ نظم سیاسی»؛ از انقلاب فرانسه تا زوال دموکراسی‌های معاصر.',
            note: null,
            finishedAt: '1405-02',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۴۰۴ ——— */
        {
            id: 'mind-and-market',
            title: 'The Mind and the Market',
            titleFa: 'ذهن و بازار',
            subtitle: 'جایگاه سرمایه‌داری در تفکر اروپای مدرن',
            author: 'Jerry Z. Muller',
            authorFa: 'جری مولر',
            year: 2002,
            rating: 4,
            avgRating: 4.17,
            pages: 512,
            genres: ['اقتصاد', 'اندیشه', 'فلسفه'],
            language: 'انگلیسی',
            cover: '',
            summary: 'تاریخ فکری سرمایه‌داری از ولتر تا هایک؛ چگونه متفکران غربی میان بازار و ذهن انسان پل زدند.',
            note: null,
            finishedAt: '1404-12-03',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'power-of-geography',
            title: 'The Power of Geography',
            titleFa: 'قدرت جغرافیا',
            subtitle: 'نقشه‌هایی که اکنون و آیندهٔ جهان را آشکار می‌کنند',
            author: 'Tim Marshall',
            authorFa: 'تیم مارشال',
            year: 2021,
            rating: 3,
            avgRating: 4.18,
            pages: 368,
            genres: ['جغرافیا', 'سیاسی', 'تاریخ'],
            language: 'انگلیسی',
            cover: '',
            summary: 'ده نقشه، ده منطقهٔ کلیدی ژئوپلیتیک؛ ادامهٔ «در اسارت جغرافیا».',
            note: null,
            finishedAt: '1404-10-10',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'grokking-algorithms',
            title: 'Grokking Algorithms',
            titleFa: 'الگوریتم‌ها به زبان ساده',
            author: 'Aditya Y. Bhargava',
            authorFa: 'آدیتیا بهارگاوا',
            year: 2016,
            rating: 4,
            avgRating: 4.41,
            pages: 256,
            genres: ['فنی', 'الگوریتم', 'برنامه‌نویسی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'مقدمه‌ای تصویری و ساده بر الگوریتم‌ها و ساختمان داده.',
            note: null,
            finishedAt: '1404-06-30',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'suicide-shop',
            title: 'The Suicide Shop',
            titleFa: 'مغازهٔ خودکشی',
            author: 'Jean Teulé',
            authorFa: 'ژان تولی',
            year: 2007,
            rating: 3,
            avgRating: 3.46,
            pages: 176,
            genres: ['طنز سیاه', 'فرانسوی'],
            language: 'فرانسوی',
            cover: '',
            summary: 'خانواده‌ای که مغازهٔ خودکشی دارد؛ تا اینکه فرزند کوچک خانواده تصمیم می‌گیرد خوشحال باشد.',
            note: null,
            finishedAt: '1404-05-30',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۴۰۳ ——— */
        {
            id: 'ddia',
            title: 'Designing Data-Intensive Applications',
            titleFa: 'طراحی برنامه‌های داده‌محور',
            subtitle: 'DDIA',
            author: 'Martin Kleppmann',
            authorFa: 'مارتین کِلپمن',
            year: 2017,
            rating: 4,
            avgRating: 4.69,
            pages: 616,
            genres: ['فنی', 'مهندسی', 'داده'],
            language: 'انگلیسی',
            cover: '',
            summary: 'کتاب مرجع معماری سیستم‌های توزیع‌شده؛ از مدل‌های داده تا اجماع و پردازش جریانی.',
            note: 'کتابی که دیدم را نسبت به معماری سیستم‌ها برای همیشه عوض کرد.',
            finishedAt: '1403-04-30',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۴۰۲ ——— */
        {
            id: 'prisoners-of-geography',
            title: 'Prisoners of Geography',
            titleFa: 'در اسارت جغرافیا',
            subtitle: 'ده نقشه که همهٔ آموختنی‌ها دربارهٔ سیاست جهانی را بیان می‌کند',
            author: 'Tim Marshall',
            authorFa: 'تیم مارشال',
            year: 2015,
            rating: 3,
            avgRating: 4.18,
            pages: 256,
            genres: ['جغرافیا', 'سیاسی', 'تاریخ'],
            language: 'انگلیسی',
            cover: '',
            summary: 'ده نقشه که نشان می‌دهد جغرافیا چگونه سیاست جهانی را شکل می‌دهد.',
            note: null,
            finishedAt: '1402-12-25',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'confessions-philosopher',
            title: 'Confessions of a Philosopher',
            titleFa: 'مواجهه با مرگ',
            author: 'Bryan Magee',
            authorFa: 'برایان مگی',
            year: 1997,
            rating: 4,
            avgRating: 3.86,
            pages: 606,
            genres: ['فلسفه', 'خودنوشت'],
            language: 'انگلیسی',
            cover: '',
            summary: 'مگی در این کتاب به پرسش‌های بنیادین فلسفی دربارهٔ مرگ و معنای زندگی می‌پردازد.',
            note: null,
            finishedAt: '1402-06-06',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'molecule-of-more',
            title: 'The Molecule of More',
            titleFa: 'دوپامین، مولکولی با خواص شگفت‌انگیز',
            author: 'Daniel Z. Lieberman',
            authorFa: 'دنیل لیبرمن',
            year: 2018,
            rating: 4,
            avgRating: 4.12,
            pages: 240,
            genres: ['علمی', 'روان‌شناسی', 'عصب‌شناسی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'چگونه دوپامین فرایندهای عشق، خلاقیت و اعتیاد را شکل می‌دهد.',
            note: null,
            finishedAt: '1402-04-13',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'letter-to-child',
            title: 'Letter to a Child Never Born',
            titleFa: 'نامه به کودکی که هرگز زاده نشد',
            author: 'Oriana Fallaci',
            authorFa: 'اوریانا فالاچی',
            year: 1975,
            rating: 3,
            avgRating: 4.04,
            pages: 118,
            genres: ['ادبی', 'ایتالیایی', 'فمینیستی'],
            language: 'ایتالیایی',
            cover: '',
            summary: 'نامه‌ای از مادر به جنینی که تصمیم می‌گیرد به دنیا نیاید؛ شاهکار فالاچی.',
            note: null,
            finishedAt: '1402-02-13',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'how-the-laser-happened',
            title: 'How the Laser Happened',
            titleFa: 'داستان لیزر',
            author: 'Charles H. Townes',
            authorFa: 'چارلز تاونز',
            year: 1999,
            rating: 2,
            avgRating: 3.83,
            pages: 208,
            genres: ['علمی', 'خودنوشت', 'فیزیک'],
            language: 'انگلیسی',
            cover: '',
            summary: 'خودنوشت چارلز تاونز، برندهٔ نوبل فیزیک و یکی از پدران لیزر.',
            note: null,
            finishedAt: '1402-01-26',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۴۰۱ ——— */
        {
            id: 'python-crash-course',
            title: 'Python Crash Course',
            titleFa: 'آموزش سریع پایتون',
            author: 'Eric Matthes',
            authorFa: 'اریک ماتیس',
            year: 2015,
            rating: 4,
            avgRating: 4.36,
            pages: 544,
            genres: ['فنی', 'برنامه‌نویسی', 'پایتون'],
            language: 'انگلیسی',
            cover: '',
            summary: 'آموزش پروژه‌محور پایتون از صفر تا ساخت بازی و وب‌اپلیکیشن.',
            note: null,
            finishedAt: '1401-06-21',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'master-margarita',
            title: 'The Master and Margarita',
            titleFa: 'مرشد و مارگریتا',
            author: 'Mikhail Bulgakov',
            authorFa: 'میخائیل بولگاکف',
            year: 1967,
            rating: 5,
            avgRating: 4.28,
            pages: 384,
            genres: ['کلاسیک', 'روسی', 'فانتزی'],
            language: 'روسی',
            cover: '',
            summary: 'شیطان به مسکو می‌آید؛ شاهکاری از بولگاکف دربارهٔ عشق، هنر و استبداد.',
            note: null,
            finishedAt: '1401-05-19',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۴۰۰ ——— */
        {
            id: 'infinite-powers',
            title: 'Infinite Powers',
            titleFa: 'زبان طبیعت',
            subtitle: 'چگونه حسابان اسرار جهان هستی را می‌گشاید',
            author: 'Steven Strogatz',
            authorFa: 'استیون استروگاتز',
            year: 2019,
            rating: 5,
            avgRating: 4.29,
            pages: 384,
            genres: ['ریاضی', 'علمی', 'تاریخ'],
            language: 'انگلیسی',
            cover: '',
            summary: 'داستان حسابان از ارشمیدس تا امروز؛ چرا این زبان، زبان طبیعت است.',
            note: null,
            finishedAt: '1400-11-05',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'drama-gifted-child',
            title: 'The Drama of the Gifted Child',
            titleFa: 'دلهره‌های کودکی',
            author: 'Alice Miller',
            authorFa: 'آلیس میلر',
            year: 1979,
            rating: 3,
            avgRating: 4.04,
            pages: 144,
            genres: ['روان‌شناسی', 'روان‌کاوی'],
            language: 'آلمانی',
            cover: '',
            summary: 'کتابی دربارهٔ آسیب‌های پنهان دوران کودکی و تأثیرشان بر بزرگسالی.',
            note: null,
            finishedAt: '1400-08-11',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'chess-for-dummies',
            title: 'Chess for Dummies',
            titleFa: 'شطرنج برای مبتدیان',
            author: 'James Eade',
            authorFa: 'جیمز اید',
            year: 1996,
            rating: 4,
            avgRating: 3.84,
            pages: 384,
            genres: ['ورزشی', 'آموزشی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'راهنمای گام‌به‌گام شطرنج برای مبتدیان.',
            note: null,
            finishedAt: '1400-06-28',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'the-plague',
            title: 'The Plague',
            titleFa: 'طاعون',
            author: 'Albert Camus',
            authorFa: 'آلبر کامو',
            year: 1947,
            rating: 4,
            avgRating: 4.02,
            pages: 308,
            genres: ['کلاسیک', 'فرانسوی', 'فلسفی'],
            language: 'فرانسوی',
            cover: '',
            summary: 'شهر اوران در محاصرهٔ طاعون؛ کامی دربارهٔ پوچی، همبستگی و معنای عمل.',
            note: null,
            finishedAt: '1400-06-24',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'sophies-world',
            title: "Sophie's World",
            titleFa: 'دنیای سوفی',
            author: 'Jostein Gaarder',
            authorFa: 'یوستین گردر',
            year: 1991,
            rating: 5,
            avgRating: 3.97,
            pages: 518,
            genres: ['فلسفه', 'رمان', 'نروژی'],
            language: 'نروژی',
            cover: '',
            summary: 'تاریخ فلسفه در قالب رمانی دربارهٔ دختری که نامه‌های عجیب دریافت می‌کند.',
            note: null,
            finishedAt: '1400-09-29',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۳۹۹ ——— */
        {
            id: 'love-time-cholera',
            title: 'Love in the Time of Cholera',
            titleFa: 'عشق در روزگار وبا',
            author: 'Gabriel García Márquez',
            authorFa: 'گابریل گارسیا مارکز',
            year: 1985,
            rating: 5,
            avgRating: 3.94,
            pages: 368,
            genres: ['کلاسیک', 'لاتین', 'رمان'],
            language: 'اسپانیایی',
            cover: '',
            summary: 'عشقی نیم‌قرنی؛ مارکز دربارهٔ عشق در سن پیری و زمان.',
            note: null,
            finishedAt: '1399-06-17',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'khookhor-deh',
            title: 'Khookhor-deh',
            titleFa: 'خون خورده',
            author: 'مهدی یزدانی خرم',
            authorFa: 'مهدی یزدانی خرم',
            year: 1395,
            rating: 3,
            avgRating: 3.83,
            pages: 320,
            genres: ['ایرانی', 'معاصر'],
            language: 'فارسی',
            cover: '',
            summary: 'رمانی از مهدی یزدانی خرم دربارهٔ تهران امروز.',
            note: null,
            finishedAt: '1399-05-15',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'deep-work',
            title: 'Deep Work',
            titleFa: 'کار عمیق',
            author: 'Cal Newport',
            authorFa: 'کال نیوپورت',
            year: 2016,
            rating: 3,
            avgRating: 4.15,
            pages: 296,
            genres: ['بهره‌وری', 'روان‌شناسی', 'کار'],
            language: 'انگلیسی',
            cover: '',
            summary: 'قواعدی برای تمرکز در دنیایی پر از حواس‌پرتی.',
            note: null,
            finishedAt: '1399-05-21',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'schopenhauer-cure',
            title: 'The Schopenhauer Cure',
            titleFa: 'درمان شوپنهاور',
            author: 'Irvin D. Yalom',
            authorFa: 'اروین یالوم',
            year: 2005,
            rating: 5,
            avgRating: 4.28,
            pages: 358,
            genres: ['روان‌شناسی', 'رمان', 'فلسفی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'یالوم در این رمان، فلسفهٔ شوپنهاور را با گروه‌درمانی پیوند می‌زند.',
            note: null,
            finishedAt: '1399-05-09',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'how-to-read-a-book',
            title: 'How to Read a Book',
            titleFa: 'چگونه کتاب بخوانیم',
            author: 'Mortimer J. Adler',
            authorFa: 'مورتیمِر آدلر',
            year: 1940,
            rating: 1,
            avgRating: 3.98,
            pages: 426,
            genres: ['آموزشی', 'کتاب‌خوانی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'راهنمای کلاسیک خواندن فعال و انتقادی.',
            note: null,
            finishedAt: '1399-05-01',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'when-nietzsche-wept',
            title: 'When Nietzsche Wept',
            titleFa: 'وقتی نیچه گریست',
            author: 'Irvin D. Yalom',
            authorFa: 'اروین یالوم',
            year: 1992,
            rating: 4,
            avgRating: 4.36,
            pages: 306,
            genres: ['روان‌شناسی', 'رمان', 'فلسفی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'یالوم در این رمان، بروئر و نیچه را در وین قرن نوزدهم به هم می‌رساند.',
            note: null,
            finishedAt: '1399-03-31',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'samphony-mordegan',
            title: 'Symphony of the Dead',
            titleFa: 'سمفونی مردگان',
            author: 'عباس معروفی',
            authorFa: 'عباس معروفی',
            year: 1368,
            rating: 4,
            avgRating: 4.28,
            pages: 368,
            genres: ['ایرانی', 'معاصر', 'رمان'],
            language: 'فارسی',
            cover: '',
            summary: 'شاهکار عباس معروفی؛ روایتی چندصدایی از خانواده‌ای در اردبیل.',
            note: null,
            finishedAt: '1399-10-20',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۳۹۸ ——— */
        {
            id: 'az-sard-va-garm',
            title: 'Az Sard va Garm-e Roozegar',
            titleFa: 'از سرد و گرم روزگار',
            author: 'احمد زیدآبادی',
            authorFa: 'احمد زیدآبادی',
            year: 1397,
            rating: 4,
            avgRating: 3.65,
            pages: 320,
            genres: ['ایرانی', 'خودنوشت', 'سیاسی'],
            language: 'فارسی',
            cover: '',
            summary: 'خودنوشت احمد زیدآبادی، روزنامه‌نگار و فعال سیاسی ایرانی.',
            note: null,
            finishedAt: '1398-02-16',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'modir-madrese',
            title: 'The School Principal',
            titleFa: 'مدیر مدرسه',
            author: 'جلال آل احمد',
            authorFa: 'جلال آل احمد',
            year: 1337,
            rating: 3,
            avgRating: 3.45,
            pages: 128,
            genres: ['ایرانی', 'کلاسیک'],
            language: 'فارسی',
            cover: '',
            summary: 'رمانی کوتاه از جلال آل احمد دربارهٔ نظام آموزشی ایران.',
            note: null,
            finishedAt: '1398-02-13',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'az-ranji-ke-mibarim',
            title: 'Az Ranji ke Mibarim',
            titleFa: 'از رنجی که می‌بریم',
            author: 'جلال آل احمد',
            authorFa: 'جلال آل احمد',
            year: 1327,
            rating: 2,
            avgRating: 3.00,
            pages: 108,
            genres: ['ایرانی', 'کلاسیک', 'داستان کوتاه'],
            language: 'فارسی',
            cover: '',
            summary: 'مجموعه داستان‌های کوتاه جلال آل احمد.',
            note: null,
            finishedAt: '1398-01-02',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۳۹۷ ——— */
        {
            id: 'hashemi-bedoun-retouch',
            title: 'Hashemi Bedoun-e Retouch',
            titleFa: 'هاشمی بدون روتوش',
            subtitle: 'گفتگو با هاشمی رفسنجانی',
            author: 'صادق زیباکلام',
            authorFa: 'صادق زیباکلام',
            year: 1393,
            rating: 4,
            avgRating: 3.57,
            pages: 400,
            genres: ['ایرانی', 'تاریخ', 'سیاسی'],
            language: 'فارسی',
            cover: '',
            summary: 'گفتگوهای صادق زیباکلام با اکبر هاشمی رفسنجانی.',
            note: null,
            finishedAt: '1397-03-15',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'brave-new-world',
            title: 'Brave New World',
            titleFa: 'دنیای قشنگ نو',
            author: 'Aldous Huxley',
            authorFa: 'آلدوس هاکسلی',
            year: 1932,
            rating: 3,
            avgRating: 3.98,
            pages: 288,
            genres: ['علمی‌تخیلی', 'دیستوپیا', 'کلاسیک'],
            language: 'انگلیسی',
            cover: '',
            summary: 'دنیایی که در آن انسان‌ها در آزمایشگاه تولید و از بدو تولد شرطی می‌شوند.',
            note: null,
            finishedAt: '1397-09-26',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'daee-jan-napoleon',
            title: 'My Uncle Napoleon',
            titleFa: 'دایی جان ناپلئون',
            author: 'ایرج پزشکزاد',
            authorFa: 'ایرج پزشکزاد',
            year: 1352,
            rating: 5,
            avgRating: 4.21,
            pages: 512,
            genres: ['ایرانی', 'طنز', 'کلاسیک'],
            language: 'فارسی',
            cover: '',
            summary: 'محبوب‌ترین رمان طنز ایرانی؛ دایی‌جانی که خود را ناپلئون می‌پندارد.',
            note: null,
            finishedAt: '1397-05-12',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'boof-koor',
            title: 'The Blind Owl',
            titleFa: 'بوف کور',
            author: 'صادق هدایت',
            authorFa: 'صادق هدایت',
            year: 1315,
            rating: 3,
            avgRating: 3.94,
            pages: 128,
            genres: ['ایرانی', 'کلاسیک', 'مدرن'],
            language: 'فارسی',
            cover: '',
            summary: 'شاهکار صادق هدایت؛ رمانی سوررئال و تأثیرگذار در ادبیات فارسی.',
            note: null,
            finishedAt: '1397-03-23',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'huckleberry-finn',
            title: 'The Adventures of Huckleberry Finn',
            titleFa: 'ماجراهای هاکلبری فین',
            author: 'Mark Twain',
            authorFa: 'مارک تواین',
            year: 1884,
            rating: 4,
            avgRating: 3.83,
            pages: 366,
            genres: ['کلاسیک', 'آمریکایی', 'ماجراجویی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'سفر هاک و جیم در امتداد رود می‌سی‌سی‌پی؛ شاهکار مارک تواین.',
            note: null,
            finishedAt: '1397-02-19',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'martian-chronicles',
            title: 'The Martian Chronicles',
            titleFa: 'شرکت سهامی آدم‌های مصنوعی',
            author: 'Ray Bradbury',
            authorFa: 'ری بردبری',
            year: 1950,
            rating: 3,
            avgRating: 4.05,
            pages: 256,
            genres: ['علمی‌تخیلی', 'کلاسیک', 'آمریکایی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'مجموعه داستان‌های بردبری دربارهٔ استعمار مریخ.',
            note: null,
            finishedAt: '1397-01-22',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'ma-chegone-ma-shodim',
            title: 'Ma Chegone Ma Shodim',
            titleFa: 'ما چگونه، ما شدیم؟',
            author: 'صادق زیباکلام',
            authorFa: 'صادق زیباکلام',
            year: 1395,
            rating: 3,
            avgRating: 3.76,
            pages: 520,
            genres: ['ایرانی', 'تاریخ', 'اندیشه'],
            language: 'فارسی',
            cover: '',
            summary: 'ریشه‌یابی عقب‌ماندگی ایران از دیدگاه صادق زیباکلام.',
            note: null,
            finishedAt: '1397-04-19',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۳۹۶ ——— */
        {
            id: 'girl-on-the-train',
            title: 'The Girl on the Train',
            titleFa: 'دختری در قطار',
            author: 'Paula Hawkins',
            authorFa: 'پائولا هاوکینز',
            year: 2015,
            rating: 3,
            avgRating: 3.96,
            pages: 336,
            genres: ['معمایی', 'هیجان‌انگیز'],
            language: 'انگلیسی',
            cover: '',
            summary: 'رمانی معمایی دربارهٔ زنی که هر روز از قطار شاهد خانه‌ای است.',
            note: null,
            finishedAt: '1396-11-22',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'adolphe',
            title: 'Adolphe',
            titleFa: 'آدلف',
            author: 'Benjamin Constant',
            authorFa: 'بنجامین کنستان',
            year: 1816,
            rating: 5,
            avgRating: 3.58,
            pages: 128,
            genres: ['کلاسیک', 'فرانسوی', 'روان‌شناختی'],
            language: 'فرانسوی',
            cover: '',
            summary: 'رمانی کوتاه از کنستان دربارهٔ عشقی که به نفرت می‌گراید.',
            note: null,
            finishedAt: '1396-10-13',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'the-clown',
            title: 'The Clown',
            titleFa: 'عقاید یک دلقک',
            author: 'Heinrich Böll',
            authorFa: 'هاینریش بل',
            year: 1963,
            rating: 1,
            avgRating: 3.92,
            pages: 256,
            genres: ['آلمانی', 'کلاسیک', 'ادبی'],
            language: 'آلمانی',
            cover: '',
            summary: 'دلقکی که علیه جامعهٔ آلمان پس از جنگ می‌شورد.',
            note: null,
            finishedAt: '1396-08-29',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'blindness',
            title: 'Blindness',
            titleFa: 'کوری',
            author: 'José Saramago',
            authorFa: 'ژوزه ساراماگو',
            year: 1995,
            rating: 4,
            avgRating: 4.19,
            pages: 352,
            genres: ['پرتغالی', 'دیستوپیا', 'ادبی'],
            language: 'پرتغالی',
            cover: '',
            summary: 'شهری که در آن همه به یک‌باره کور می‌شوند.',
            note: null,
            finishedAt: '1396-07-26',
            startedAt: null,
            goodreads: null,
        },
        {
            id: '100-year-old-man',
            title: 'The 100-Year-Old Man Who Climbed Out the Window and Disappeared',
            titleFa: 'پیرمرد صد ساله‌ای که از پنجره بیرون پرید و ناپدید شد',
            author: 'Jonas Jonasson',
            authorFa: 'یوناس یوناسون',
            year: 2009,
            rating: 4,
            avgRating: 3.82,
            pages: 384,
            genres: ['کمدی', 'سوئدی', 'ماجراجویی'],
            language: 'سوئدی',
            cover: '',
            summary: 'پیرمردی که در روز تولد ۱۰۰ سالگی‌اش از خانهٔ سالمندان فرار می‌کند.',
            note: null,
            finishedAt: '1396-10-07',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'nezam-novin-rohaniyat',
            title: 'The New Order of the Clergy in Iran',
            titleFa: 'نظم نوین روحانیت در ایران',
            author: 'Mehdi Khalaji',
            authorFa: 'مهدی خلجی',
            year: 1395,
            rating: 3,
            avgRating: 3.81,
            pages: 280,
            genres: ['ایرانی', 'سیاسی', 'تاریخ'],
            language: 'فارسی',
            cover: '',
            summary: 'تحلیلی از تحول ساختار روحانیت شیعه در ایران معاصر.',
            note: null,
            finishedAt: '1396-11-30',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'man-called-ove',
            title: 'A Man Called Ove',
            titleFa: 'مردی به نام اوه',
            author: 'Fredrik Backman',
            authorFa: 'فردریک بکمن',
            year: 2012,
            rating: 5,
            avgRating: 4.38,
            pages: 337,
            genres: ['سوئدی', 'رمان', 'کمدی'],
            language: 'سوئدی',
            cover: '',
            summary: 'پیرمردی بداخلاق که دنیایش با ورود یک خانوادهٔ جدید تغییر می‌کند.',
            note: null,
            finishedAt: '1396-07-28',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'third-wave',
            title: 'The Third Wave',
            titleFa: 'موج سوم',
            author: 'Alvin Toffler',
            authorFa: 'آلوین تافلر',
            year: 1980,
            rating: 5,
            avgRating: 3.96,
            pages: 544,
            genres: ['آینده‌پژوهی', 'جامعه‌شناسی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'تافلر در این کتاب، تحول جوامع از کشاورزی تا صنعتی و پساصنعتی را تحلیل می‌کند.',
            note: null,
            finishedAt: '1396-05-18',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'all-quiet-western-front',
            title: 'All Quiet on the Western Front',
            titleFa: 'در غرب خبری نیست',
            author: 'Erich Maria Remarque',
            authorFa: 'اریش ماریا رمارک',
            year: 1929,
            rating: 5,
            avgRating: 4.12,
            pages: 296,
            genres: ['آلمانی', 'جنگ', 'کلاسیک'],
            language: 'آلمانی',
            cover: '',
            summary: 'روایتی تکان‌دهنده از جنگ جهانی اول از دید یک سرباز آلمانی.',
            note: null,
            finishedAt: '1396-02-03',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'old-man-sea',
            title: 'The Old Man and the Sea',
            titleFa: 'پیرمرد و دریا',
            author: 'Ernest Hemingway',
            authorFa: 'ارنست همینگوی',
            year: 1952,
            rating: 4,
            avgRating: 3.82,
            pages: 127,
            genres: ['کلاسیک', 'آمریکایی', 'ادبی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'پیرماهیگیر کوبایی و نبردش با یک ماهی بزرگ؛ شاهکار همینگوی.',
            note: null,
            finishedAt: '1396-02-05',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۳۹۵ ——— */
        {
            id: 'georges-secret-key',
            title: "George's Secret Key to the Universe",
            titleFa: 'انفجار بزرگ',
            author: 'Lucy Hawking',
            authorFa: 'لوسی هاوکینگ',
            year: 2007,
            rating: 1,
            avgRating: 4.22,
            pages: 297,
            genres: ['کودک', 'علمی', 'نجوم'],
            language: 'انگلیسی',
            cover: '',
            summary: 'کتابی برای کودکان دربارهٔ کیهان‌شناسی، نوشتهٔ لوسی هاوکینگ و استیون هاوکینگ.',
            note: null,
            finishedAt: '1395-07-02',
            startedAt: null,
            goodreads: null,
        },

        /* ——— ۱۳۹۴ ——— */
        {
            id: 'look-whos-back',
            title: "Look Who's Back",
            titleFa: 'او بازگشته است',
            author: 'Timur Vermes',
            authorFa: 'تیمور ورمش',
            year: 2012,
            rating: 4,
            avgRating: 3.43,
            pages: 400,
            genres: ['آلمانی', 'طنز سیاه', 'سیاسی'],
            language: 'آلمانی',
            cover: '',
            summary: 'هیتلر در برلین امروز بیدار می‌شود؛ رمانی طنز و هشداردهنده.',
            note: null,
            finishedAt: '1394-11-04',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'pedar-madar-mottahemim',
            title: 'We Are All to Blame',
            titleFa: 'پدر، مادر، ما متهمیم',
            author: 'Ali Shariati',
            authorFa: 'علی شریعتی',
            year: 1357,
            rating: null,
            avgRating: 3.66,
            pages: 200,
            genres: ['ایرانی', 'اندیشه', 'مذهبی'],
            language: 'فارسی',
            cover: '',
            summary: 'مجموعه‌ای از سخنرانی‌های علی شریعتی دربارهٔ مسئولیت نسل.',
            note: null,
            finishedAt: '1394-01-11',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'housekeeper-professor',
            title: 'The Housekeeper and the Professor',
            titleFa: 'خدمتکار و پروفسور',
            author: 'Yōko Ogawa',
            authorFa: 'یوکو اوگاوا',
            year: 2003,
            rating: 2,
            avgRating: 4.04,
            pages: 180,
            genres: ['ژاپنی', 'ادبی', 'ریاضی'],
            language: 'ژاپنی',
            cover: '',
            summary: 'داستان خدمتکاری که از پروفسوری با حافظهٔ هشتاددقیقه‌ای مراقبت می‌کند.',
            note: null,
            finishedAt: '1394-03-02',
            startedAt: null,
            goodreads: null,
        },

        /* ——— پیش از ۱۳۹۴ ——— */
        {
            id: 'alchemist',
            title: 'The Alchemist',
            titleFa: 'کیمیاگر',
            author: 'Paulo Coelho',
            authorFa: 'پائولو کوئیلو',
            year: 1988,
            rating: 5,
            avgRating: 3.92,
            pages: 208,
            genres: ['برزیلی', 'رمان', 'فلسفی'],
            language: 'پرتغالی',
            cover: '',
            summary: 'سفر چوپانی اسپانیایی به سمت گنج؛ رمانی دربارهٔ رؤیاها و سرنوشت.',
            note: null,
            finishedAt: '1395-01-25',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'animal-farm',
            title: 'Animal Farm',
            titleFa: 'قلعهٔ حیوانات',
            author: 'George Orwell',
            authorFa: 'جورج اورول',
            year: 1945,
            rating: 5,
            avgRating: 4.03,
            pages: 112,
            genres: ['کلاسیک', 'سیاسی', 'تمثیلی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'تمثیلی از انقلاب روسیه با شخصیت‌های حیوانی.',
            note: null,
            finishedAt: '1393-09-24',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'journey-center-earth',
            title: 'Journey to the Center of the Earth',
            titleFa: 'سفر به اعماق زمین',
            author: 'Jules Verne',
            authorFa: 'ژول ورن',
            year: 1864,
            rating: 5,
            avgRating: 3.85,
            pages: 192,
            genres: ['کلاسیک', 'فرانسوی', 'ماجراجویی'],
            language: 'فرانسوی',
            cover: '',
            summary: 'پروفسور لیدنبروک و برادرزاده‌اش به مرکز زمین سفر می‌کنند.',
            note: null,
            finishedAt: '1384-09-27',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'story-of-my-life',
            title: 'The Story of My Life',
            titleFa: 'داستان زندگی من',
            author: 'Helen Keller',
            authorFa: 'هلن کلر',
            year: 1903,
            rating: 4,
            avgRating: 4.07,
            pages: 100,
            genres: ['خودنوشت', 'آمریکایی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'خودنوشت هلن کلر، زنی که ناشنوا و نابینا بود و نویسنده شد.',
            note: null,
            finishedAt: '1386-05-15',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'benjamin-franklin',
            title: 'Benjamin Franklin: Scientist and Statesman',
            titleFa: 'بنجامین فرانکلین: دانشمند و دولتمرد',
            author: 'Brenda Haugen',
            authorFa: 'برندا هوگن',
            year: null,
            rating: 5,
            avgRating: 3.64,
            pages: 112,
            genres: ['زندگی‌نامه', 'تاریخ', 'آمریکایی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'زندگی‌نامهٔ بنجامین فرانکلین برای نوجوانان.',
            note: null,
            finishedAt: '1386-03',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'peaks-and-valleys',
            title: 'Peaks and Valleys',
            titleFa: 'قله‌ها و دره‌ها',
            author: 'Spencer Johnson',
            authorFa: 'اسپنسر جانسون',
            year: 2009,
            rating: 4,
            avgRating: 4.04,
            pages: 112,
            genres: ['بهره‌وری', 'انگیزشی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'داستانی دربارهٔ چگونگی مدیریت دوره‌های خوب و بد زندگی.',
            note: null,
            finishedAt: '1395-04',
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'formula',
            title: 'The Formula',
            titleFa: 'فرمول',
            subtitle: 'قوانین جهانی موفقیت',
            author: 'Albert-László Barabási',
            authorFa: 'آلبرت لازلو باراباشی',
            year: 2018,
            rating: 2,
            avgRating: 4.17,
            pages: 320,
            genres: ['علمی', 'موفقیت', 'شبکه'],
            language: 'انگلیسی',
            cover: '',
            summary: 'باراباشی با نگاه شبکه‌ای، قوانین موفقیت را بررسی می‌کند.',
            note: null,
            finishedAt: null,
            startedAt: null,
            goodreads: null,
        },
        {
            id: 'nineteen-eighty-four',
            title: 'Nineteen Eighty-Four',
            titleFa: '۱۹۸۴',
            author: 'George Orwell',
            authorFa: 'جورج اورول',
            year: 1949,
            rating: 5,
            avgRating: 4.21,
            pages: 328,
            genres: ['دیستوپیا', 'کلاسیک', 'سیاسی'],
            language: 'انگلیسی',
            cover: '',
            summary: 'شاهکار اورول دربارهٔ حکومت تمامیت‌خواه و برادر بزرگ.',
            note: null,
            finishedAt: null,
            startedAt: null,
            goodreads: null,
        },
    ],

    /* ---------- مقالات علمی ---------- */
    /* ---------- مقالات علمی ---------- */
    /* فیلدها:
       - status    read | reading | planned
       - readAt    تاریخ خواندن (شمسی، YYYY-MM)
       - url       لینک اصلی (arXiv یا DOI)
       - ieee      لینک IEEE (اگر موجود باشد)
       - pdf       لینک مستقیم PDF
    */
    papers: [
        {
            id: 'faiss-billion-scale',
            title: 'Billion-scale similarity search with GPUs',
            titleFa: 'جستجوی شباهت در مقیاس میلیاردی با GPU',
            authors: ['Jeff Johnson', 'Matthijs Douze', 'Hervé Jégou'],
            year: 2017,
            venue: 'IEEE Transactions on Big Data',
            venueShort: 'IEEE',
            url: 'https://arxiv.org/abs/1702.08734',
            ieee: 'https://ieeexplore.ieee.org/document/8736019',
            doi: '10.1109/TBDATA.2019.2921572',
            pdf: 'https://arxiv.org/pdf/1702.08734',
            tags: ['Vector Search', 'ANN', 'GPU', 'FAISS'],
            summary: 'معرفی کتابخانهٔ FAISS و الگوریتم‌های ایندکس‌گذاری برداری برای جستجو در مقیاس میلیاردی؛ شامل IVF، PQ و نسخهٔ GPU.',
            takeaway: 'مرجع اصلی FAISS؛ پایهٔ تمام موتورهای جستجوی برداری مدرن.',
            status: 'read',
            readAt: '1404-02',
            note: 'پایهٔ دورهٔ FAISS که ضبط کردم.',
        },
        {
            id: 'kg-llm-survey',
            title: 'Unifying Large Language Models and Knowledge Graphs: A Roadmap',
            titleFa: 'یکپارچه‌سازی مدل‌های زبانی بزرگ و گراف‌های دانش',
            subtitle: 'A Roadmap',
            authors: ['Shirui Pan', 'Linhao Luo', 'Yufei Wang', 'Chen Chen', 'Jiapu Wang', 'Xindong Wu'],
            year: 2024,
            venue: 'IEEE Transactions on Knowledge and Data Engineering',
            venueShort: 'IEEE TKDE',
            url: 'https://arxiv.org/abs/2306.08302',
            ieee: 'https://ieeexplore.ieee.org/document/10506677',
            doi: '10.1109/TKDE.2024.3390094',
            pdf: 'https://arxiv.org/pdf/2306.08302',
            tags: ['LLM', 'Knowledge Graph', 'Survey', 'RAG'],
            summary: 'مرور جامع بر سه رویکرد یکپارچه‌سازی KG و LLM: KG-enhanced LLMs، LLM-augmented KGs، و هم‌افزایی همزمان.',
            takeaway: 'نقشهٔ راه برای ترکیب دانش ساخت‌یافته با مدل‌های زبانی.',
            status: 'read',
            readAt: '1403-09',
            note: 'لینک IEEE را باید از پروفایل شخصی‌ام استخراج کنم.',
        },
        {
            id: 'attention-is-all-you-need',
            title: 'Attention Is All You Need',
            titleFa: 'توجه، تمام آن چیزی است که نیاز دارید',
            authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit', 'Llion Jones', 'Aidan N. Gomez', 'Łukasz Kaiser', 'Illia Polosukhin'],
            year: 2017,
            venue: 'NeurIPS',
            venueShort: 'NeurIPS',
            url: 'https://arxiv.org/abs/1706.03762',
            ieee: null,
            doi: null,
            pdf: 'https://arxiv.org/pdf/1706.03762',
            tags: ['NLP', 'Transformer', 'Deep Learning'],
            summary: 'معرفی معماری Transformer که بر پایهٔ self-attention بنا شده و RNN و CNN را در ترجمهٔ ماشینی کنار می‌زند.',
            takeaway: 'کل انقلاب LLM از این مقاله شروع شد.',
            status: 'read',
            readAt: '1402',
            note: null,
        },
        {
            id: 'agentic-ai-survey',
            title: 'Agentic AI: Autonomous Intelligence for Complex Goals – A Comprehensive Survey',
            titleFa: 'هوش عامل‌محور: هوش خودمختار برای اهداف پیچیده',
            subtitle: 'A Comprehensive Survey',
            authors: ['S. Sapkota', 'R. S. Y. R. Reddy', 'M. A. Hussien', 'A. B. M. A. Islam'],
            year: 2025,
            venue: 'IEEE Access',
            venueShort: 'IEEE Access',
            url: 'https://ieeexplore.ieee.org/document/10887284',
            ieee: 'https://ieeexplore.ieee.org/document/10887284',
            doi: '10.1109/ACCESS.2025.3544117',
            pdf: null,
            tags: ['Agentic AI', 'LLM', 'Autonomous Agents', 'Survey'],
            summary: 'مرور جامع بر معماری‌ها، چارچوب‌ها و چالش‌های سیستم‌های هوش عامل‌محور خودمختار برای اهداف پیچیده.',
            takeaway: 'نقشهٔ راه برای درک نسل بعدی سیستم‌های خودمختار مبتنی بر LLM.',
            status: 'planned',
            readAt: null,
            note: 'احتمالاً در سال آیندهٔ میلادی می‌خوانم.',
        },
    ],

    /* ---------- بازی‌ها ---------- */
    /* ---------- بازی‌ها ---------- */
    games: [
        {
            id: 'cyberpunk-2077',
            title: 'Cyberpunk 2077',
            titleFa: 'سایبرپانک ۲۰۷۷',
            year: 2020,
            rating: 86,
            ratingSource: 'Metacritic (PS5)',
            developer: 'CD Projekt Red',
            publisher: 'CD Projekt',
            platforms: ['PlayStation 5', 'PC', 'Xbox Series'],
            genres: ['Action RPG', 'Open World', 'Sci-Fi'],
            status: 'playing',
            playtime: null,
            cover: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_600x900.jpg',
            summary: 'یک نقش‌آفرینی جهان‌باز در شهر نایت‌سیتی؛ داستان V، مزدوری که به تراشه‌ای با شخصیت جانی سیلورهند آلوده شده.',
            note: 'این روزها روی PS5 ادامه می‌دهم.',
            playedAt: '1405-06',
            igdb: null,
        },
    ],
};